### ISSUE TITLE
implement loader page

### ISSUE THREAD

**Issue by ganeshbirajdar09** [EmotionWebb/facial-expressions-detection#1]
@detronetdip please have a look at this - `https://codepen.io/z-/pen/wvBPvby`

**Comment by detronetdip** [comment]
Done. Drafting a pull reuest soon!

**Comment by ganeshbirajdar09** [comment]
Yep 👍

**Comment by detronetdip** [comment]
@ganeshbirajdar09 please review #2

**Comment by ganeshbirajdar09** [comment]
@detronetdip nice, it looks great 👍

**Comment by ganeshbirajdar09** [comment]
@adityagandhamal please have a look at the loader.
